export enum ICommon {
    DATA_SOURCE = 'DATA_SOURCE',
    DATABASE = 'postgres',
    PHOTO_REPOSITORY = 'PHOTO_REPOSITORY',
    ROLE_REPOSITORY = 'ROLE_REPOSITORY',
    USER_INFO_REPOSITORY = 'USER_INFO_REPOSITORY',
    USER_PROFILE_REPOSITORY = 'USER_PROFILE_REPOSITORY',
    LANGUAGE_REPOSITORY = 'LANGUAGE_REPOSITORY',
    LANGUAGE_LEVEL_REPOSITORY = 'LANGUAGE_LEVEL_REPOSITORY',
    LANGUAGE_COMMON_REPOSITORY = 'LANGUAGE_COMMON_REPOSITORY',
    STUDY_STATUS_REPOSITORY = 'STUDY_STATUS_REPOSITORY',
    STUDY_TYPE_REPOSITORY = 'STUDY_TYPE_REPOSITORY',
    STUDY_REPOSITORY = 'STUDY_REPOSITORY',
    COMPANY_REPOSITORY = 'COMPANY_REPOSITORY',
    PUBLICATION_REPOSITORY = 'PUBLICATION_REPOSITORY',
    PUBLICATION_DETAIL_REPOSITORY = 'PUBLICATION_DETAIL_REPOSITORY',
    PUBLICATION_TYPE_REPOSITORY = 'PUBLICATION_TYPE_REPOSITORY',
    PUBLICATION_DAY_TYPE_REPOSITORY = 'PUBLICATION_DAY_TYPE_REPOSITORY',
    APPLICATION_REPOSITORY = 'APPLICATION_REPOSITORY',
    GENRE_REPOSITORY = 'GENRE_REPOSITORY',
    CIVIL_STATUS_REPOSITORY = 'CIVIL_STATUS_REPOSITORY'
}

export interface IUserExpress {
    role: string;
    sub: number;
    iat: number;
    exp: number;
}